---
bibliography: references.bib
---

# Syllabus

**Course Number**: BTPS1210BA-E\
**Credits**: 2\
**Course type**: Practical\
**Year**: 2023/24/1, Semester 1 (Autumn)\
**Class Location**: P/106/A, Institute of Psychology, University of Debrecen\
**Meeting Times**: Wednesday 14:00 - 15:40\
**Contact Information**: Please contact me through email anytime: [abari.kalman\@arts.unideb.hu](mailto:abari.kalman@arts.unideb.hu){.email}

## Course overview

During the course, students will acquire the basic digital skills they will need for their studies. The course attempts to balance the knowledge levels of students with different backgrounds. At the beginning of the course, students will learn basic methods of word processing, spreadsheet and presentation design. 

The main purpose of the course is to support statistics courses. Today, statistical analysis is carried out by computer, so knowledge of one (or more) statistical software packages is essential. The rest of the course, students will be introduced to the *jamovi* statistical software and will also be introduced to the use of *R/RStudio*. The *jamovi* part of the course will cover statistical processes of data entry and data preparation, descriptive analysis, and graphic analysis. In *RStudio* students will be able to create markdown-based documents and generate HTML documents.


## Attendance

Active participation is an important part of this class. Attendance are required. The maximum number of absences from the practical sessions is three. If the student exceeds the maximum number of absences, a practical grade will not be given and a "refused" will be entered in the electronic learning system.

## Assessment and Grades

During the semester there will be 4 homework assignments and one project. The homework is independent work, the project can be done in groups of up to 3 students. Extra points can be earned by working in class, presenting a Kahoot! test or winning a Kahoot! test (3 points each).

| Components                 | Points |
|----------------------------|--------|
| Homework 1                 | 15     |
| Homework 2                 | 15     |
| Homework 3                 | 15     |
| Homework 4                 | 15     |
| Project final artifact     | 30     |
| Project final presentation | 10     |
| TOTAL                      | 100    |

: Points {.striped .hover .w-auto .mx-auto}

| Points     | Grade offered    |
|------------|------------------|
| 0--50      | 1 (failed)       |
| 51--60     | 2                |
| 61--74     | 3                |
| 75--85     | 4                |
| 86--       | 5                |

: Grading {.striped .hover .w-auto .mx-auto}

## Course details

| Day     | Topic                                        | Links                         |
|------------------|-----------------------------------|------------------|
| Sept 6  | Intro                                        | [Details](details.qmd#sec-01) |
| Sept 13 | Files, directories, compressing              | [Details](details.qmd#sec-02) |
| Sept 20 | RStudio reporting: markdown, Quarto document | [Details](details.qmd#sec-03) |
| Sept 27 | TXT, CSV, Spreadsheets                       | [Details](details.qmd#sec-04) |
| Oct 4   | Jamovi - Introduction                        | [Details](details.qmd#sec-05) |
| Oct 11  | Jamovi - Import data, Data conversion        | [Details](details.qmd#sec-06) |
| Oct 18  | Jamovi - Data transformation                 | [Details](details.qmd#sec-07) |
| Oct 25  | Jamovi - Descriptive statistics I.           | [Details](details.qmd#sec-08) |
| Nov 1   | Jamovi - Descriptive statistics II.          | [Details](details.qmd#sec-09) |
| Nov 8   | JabRef - Bibliography management             | [Details](details.qmd#sec-10) |
| Nov 15  | Word - Styles, TOC, Bibliography, APA7       | [Details](details.qmd#sec-11) |
| Nov 22  | Presentation: Power Point                    | [Details](details.qmd#sec-12) |
| Nov 29  | Project presentation                         | [Details](details.qmd#sec-13) |

: Course details {.striped .hover .w-auto .mx-auto}

## Textbooks

-   **Required:**
    -   @uoh2023 [1 Introduction, Advanced studies: presenting data]
    -   @Navarro2018 [1-117]
    -   @Poulson2019 [Getting started, Wrangling data, Exploration]
-   **Optional texts:**
    -   @Cote2021 [1-77]
    -   @Sarty2023 [1-109]

## Software

The course requires some [software](software.qmd).

## Prerequisites

No prerequisite is required. Prior knowledge in computer literacy (word processing, spreadsheets, presentation) is recommended but not required.
